### ISSUE TITLE
[feat] Recipe compiler

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/startingpoint#156]
I just made this issue to document the idea of a recipe compiler for this project, similar to Vanilla OS'es [Vib](https://github.com/Vanilla-OS/Vib). It could be an amazing idea considering it could be supported by [Zerolayer](https://github.com/akdev1l/zerolayer) for self-sufficient updates without any kind of hosting!

**Comment by gerblesh** [comment]
I agree, this would need a lot of work to get working, and we would most likely have to move away from shell, to something like go, python, or even rust. I'd say we should probably just stick to python, as it's pretty accessible and is architecture agnostic/interpreted

**Comment by xynydev** [comment]
I already have plans for this idea, great that it's an issue now so I can report here. I want to use a compiled & strongly typed language so no python. Probably prototype in nimlang but can change later if wanted. My initial idea is to leverage the bling container to house the module's as shell scripts which we can just call with RUN in the Containerfile. This would vastly simplify development.

**Comment by mirkobrombin** [comment]
Why not join forces and collaborate together in Vib? ☺️

**Comment by xynydev** [comment]
> Why not join forces and collaborate together in Vib? ☺️

They have a different config format and are under a different project, I think some healthy competition is cool and all. Besides, correct me if I'm wrong, but I doubt they'd be willing to support building OS' not built on top of Vanilla. If you present some good counterarguments, I will reconsider though.

**Comment by mirkobrombin** [comment]
Tbh, even if I named it Vib, it can be used to build images based on top of every Linux distribution, that's why the `base` key is exposed:

```yaml
base: whatever/image:branch # <--
name: Whatever OS
id: whatever-id
labels:
  maintainer: Whatever OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
  - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
modules:
  - name: init-setup
    type: shell
    commands:
...
```
