### ISSUE TITLE
Recommend using auto PR application and templates, instead of forking

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/startingpoint#224]
[github.com/wei/pull](https://github.com/wei/pull)

We can configure this application to automatically make PRs to compare `ublue-os/startingpoint -> <user's repo>`

What this would fix:

- User's accidentally making a pull request to ublue-os/startingpoint instead of their own repo
- Make it easier for the user of the template to keep their repo up-to-date, due to auto PRs that they just have to merge
- Eliminate the need for a template branch

Config file that I use at `/.github/pull.yml`:
```yml
version: "1"
rules:
  - base: main
    upstream: ublue-os:template
    mergeMethod: rebase
    mergeUnstable: false
```
