### ISSUE TITLE
Gitlab CI

### ISSUE THREAD

**Issue by grugel-maintro** [ublue-os/startingpoint#55]
Would be amazing to get a gitlab-ci.yml file to make it easy to deploy over gitlab. Im currently struggeling with the image verification and was to stupid to make a gitlab-ci pipeline that is using cosign to sign the image

**Comment by simon-truhter** [comment]
have you added the signing secret? (cosign.key content)  also you may need to add secrets for your image repository where to push it (no clue how gitlab does this). 

according to the docs it should look like (example not tested!)

```
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
```
https://docs.gitlab.com/ee/user/packages/container_registry/build_and_push_images.html

if you show us were ur stuck with an error output someone more familiar with gitlab my assist you better.
i have no clue regarding gitlab.
